server: 
  undertow:
    io-threads: 10
    worker-threads: 100
  max-http-header-size: 314572800
  port: 80

spring: 
  mvc:
    servlet:
      load-on-startup: 0
  aop:
    proxy-target-class: true
  datasource: 
    druid: 
      enable: true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      defaultAutoCommit: false
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      fail-fast: true
      timeBetweenEvictionRunsMillis: 6000
      minEvictableIdleTimeMillis: 300000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 10000
      filters: stat,wall,log4j
      useGlobalDataSourceStat: true
      stat-view-servlet:
        enabled: true
        reset-enable: false
        login-username: pengjieran
        login-password: 123456
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    pool:
      min-idle: 50
      max-idle: 500
      max-active: 2000
      max-wait: 6000
        
mybatis-plus: 
  mapper-locations: classpath*:/com/mtoliv/mapper/xml/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mtoliv.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    