spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      auto-commit: false
mybatis-plus:
  global-config:
    banner: false

