spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      auto-commit: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
mybatis-plus:
  global-config:
    banner: false