spring: 
  datasource:
    druid:
      name: edurp
      db-type: mysql
      driver-class-name: com.mysql.jdbc.Driver
      enable: true
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
      defaultAutoCommit: false
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000
      timeBetweenEvictionRunsMillis: 6000
      minEvictableIdleTimeMillis: 300000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 10000
      filters: stat,wall
      useGlobalDataSourceStat: true
      stat-view-servlet:
        enabled: true
        reset-enable: false
        login-username: pengjieran
        login-password: 123456
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  